
name: System Tests

on:
  push:
    paths: "src/**"
  pull_request:
    paths: "src/**"
  workflow_dispatch:

jobs:
  system_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Make
      run: sudo apt-get update && sudo apt-get install -y make g++ libboost-all-dev

    - name: Build and run application
      run: make run
