
name: Unit Tests

on:
  push:
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Make
      run: sudo apt-get update && sudo apt-get install -y make g++ libboost-all-dev

    - name: Run tests
      run: make test
