name: Update Submodules

on:
  workflow_dispatch:
  schedule: # everyday at midnight
    - cron: '0 0 * * *' # minute hour day-of-month month day-of-week

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "github-actions@github.com"

    - name: Update submodules to latest commit on their tracked branches
      run: |
        git submodule update --remote --merge
        git add .
        git commit -m "chore: Update submodules to latest commits on their branches" || echo "No changes to commit"
        git push origin || echo "No changes to push"
