name: Update colorfiles

on:
  workflow_dispatch:
  schedule: # everyday at midnight
    - cron: '0 0 * * *' # minute hour day-of-month month day-of-week

jobs:
  update_colorfiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "github-actions@github.com"

    # name: Update submodule
    - run: cd colorfiles
    - run: git fetch
    - run: git pull
    - run: cd ..
    - run: git add colorfiles
    - run: | # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          git commit -m "Update colorfiles submodule"
          git push
        else
          echo "No changes to commit."
        fi