name: Update colorfiles

on:
  workflow_dispatch:
  schedule: # everyday at midnight
    - cron: '0 0 * * *' # minute hour day-of-month month day-of-week

permissions:
  contents: write # Required to push changes to the repository

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Update colorfiles
      run: |
        rm -rf colorfiles
        git clone --depth 1 https://github.com/RENoMafex/grcpp_colorfiles.git colorfiles
        rm -rf colorfiles/.git
        git add --all
        git commit -m "chore: Update colorfiles" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
